name: Run dissect.py Once

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python packages
        run: |
          set -eux
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute dissect.py
        env:
          KEEPA_API_KEY                   : ${{ secrets.KEEPA_API_KEY }}
          SP_API_REFRESH_TOKEN            : ${{ secrets.SP_API_REFRESH_TOKEN }}
          LWA_APP_ID                      : ${{ secrets.LWA_APP_ID }}
          LWA_CLIENT_SECRET               : ${{ secrets.LWA_CLIENT_SECRET }}
          URI                             : ${{ secrets.URI }}
          DATABASE_NAME                   : ${{ secrets.DATABASE_NAME }}
          ERROR_COLLECTION                : ${{ secrets.ERROR_COLLECTION }}
          PRODUCT_ANALYSIS_COLLECTION     : ${{ secrets.PRODUCT_ANALYSIS_COLLECTION }}
          PRODUCT_COLLECTION              : ${{ secrets.PRODUCT_COLLECTION }}
          PRODUCT_INVENTORY_COLLECTION    : ${{ secrets.PRODUCT_INVENTORY_COLLECTION }}
        run: python dissect.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: Push changes
        run: git push origin main
